# Generated by Django 4.2.4 on 2023-10-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('not_a_boring_blog', '0018_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
