# Generated by Django 4.2.4 on 2023-10-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('not_a_boring_blog', '0019_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
